# Project information
site_name: 'Praetorian API'
site_description: 'Centralizovaná správa a distribúcia citlivých prístupových údajov'
site_author: 'Adam Žúrek'
site_url: 'https://zurek11.github.io/praetorian-api/'

# Navigation
nav:
  - Domov: index.md
  - Podporované konfigurácie: supported_configurations.md
  - Podporované prístupy: access_sources.md
  - Funkcie: features.md
  - Zabezpečenie: security.md
  - EER diagram: eer_diagram.md
  - Vizualizácia nasadenia: deploy_example.md

# Repository
repo_name: 'zurek11/praetorian-api'
repo_url: 'https://github.com/zurek11/praetorian-api'

# Configuration
theme:
  name: 'material'
  language: 'sk'
  features:
    - instant

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
