# Project information
site_name: 'Praetorian API'
site_description: 'Centralizovaná správa a distribúcia citlivých prístupových údajov'
site_author: 'Adam Žúrek'
site_url: 'https://zurek11.github.io/praetorian-api/'

# Navigation
nav:
  - Domov: index.md
  - Podporované služby: supported_services.md
  - Autentifikácia: authentication.md
  - Funkcie: features.md
  - Zabezpečenie: security.md
  - EER diagram: eer_diagram.md

# Repository
repo_name: 'zurek11/praetorian-api'
repo_url: 'https://github.com/zurek11/praetorian-api'

# Configuration
theme:
  name: 'material'
  language: 'sk'
  features:
    - instant
    - tabs

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
