# Generated by Django 3.1.1 on 2020-10-07 15:26

import apps.core.fields.aes_json_field
import apps.core.fields.aes_text_field
import apps.core.managers.user
import apps.core.models.service
import apps.core.models.user
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('name', models.CharField(max_length=100, verbose_name='user_name')),
                ('surname', models.CharField(max_length=100, verbose_name='user_surname')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='user_email')),
                ('is_active', models.BooleanField(default=False, verbose_name='user_is_active')),
                ('is_vpn', models.BooleanField(default=False, verbose_name='user_is_vpn')),
                ('is_2fa', models.BooleanField(default=False, verbose_name='user_is_2fa')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='user_is_temporary')),
                ('source', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('ldap', 'ldap'), ('db', 'db')], default=apps.core.models.user.User.Source['DB'], enum_class=apps.core.models.user.User.Source, max_length=4, verbose_name='user_source')),
                ('phone', apps.core.fields.aes_text_field.AesTextField(null=True, verbose_name='user_phone')),
                ('additional_data', models.JSONField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'default_permissions': (),
            },
            managers=[
                ('objects', apps.core.managers.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='device_name')),
                ('certificate', apps.core.fields.aes_text_field.AesTextField(max_length=50, verbose_name='device_certificate')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='project_name')),
                ('is_vpn', models.BooleanField(default=False, verbose_name='project_is_vpn')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='service_name')),
                ('type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('db', 'db')], default=apps.core.models.service.Service.ServiceType['DB'], enum_class=apps.core.models.service.Service.ServiceType, max_length=2, verbose_name='service_type')),
                ('variables', apps.core.fields.aes_json_field.AesJSONField(null=True, verbose_name='service_variables')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProjectDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='core.device', verbose_name='devices')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_devices', to='core.project', verbose_name='projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_devices', to='core.user', verbose_name='users')),
            ],
            options={
                'verbose_name': 'users_projects_devices',
                'verbose_name_plural': 'users_projects_devices',
                'db_table': 'users_projects_devices',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='remote_name')),
                ('host', apps.core.fields.aes_text_field.AesTextField(verbose_name='remote_host')),
                ('port', apps.core.fields.aes_text_field.AesTextField(verbose_name='remote_port')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to='core.service', verbose_name='remote_services')),
            ],
            options={
                'verbose_name': 'remote',
                'verbose_name_plural': 'remotes',
                'db_table': 'remotes',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='remotes',
            field=models.ManyToManyField(related_name='projects', to='core.Remote', verbose_name='projects_remotes'),
        ),
    ]
