# Generated by Django 3.2.23 on 2024-01-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_users', to='core.user', verbose_name='user_creator'),
        ),
        migrations.AlterField(
            model_name='log',
            name='base_log',
            field=models.JSONField(default=dict, null=True, verbose_name='log_log_base'),
        ),
    ]
