# Generated by Django 3.2.24 on 2024-03-30 21:21

import apps.core.models.auth_source
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_user_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='auth_source_name')),
                ('driver', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('db', 'db'), ('ldap', 'ldap')], default=apps.core.models.auth_source.AuthSource.DriverEnum['DB'], enum_class=apps.core.models.auth_source.AuthSource.DriverEnum, max_length=4, verbose_name='auth_source_driver')),
                ('content', models.JSONField(default=dict, verbose_name='auth_source_content')),
                ('is_active', models.BooleanField(default=False, verbose_name='auth_source_is_active')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sources', to='core.user', verbose_name='auth_source_creator')),
            ],
            options={
                'verbose_name': 'auth_source',
                'verbose_name_plural': 'auth_sources',
                'db_table': 'auth_sources',
                'default_permissions': ('view', 'add', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='AuthSourceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external', models.CharField(max_length=200, null=True, verbose_name='auth_source_group_external')),
                ('auth_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.authsource')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='auth.group')),
            ],
            options={
                'verbose_name': 'auth_source_group',
                'verbose_name_plural': 'auth_source_groups',
                'db_table': 'auth_source_groups',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.ForeignKey(default='cb5e7f24-3001-41f0-addc-75addcc58cbe', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.authsource', verbose_name='user_auth_source'),
            preserve_default=False,
        ),
    ]
