# Generated by Django 3.2.25 on 2024-04-12 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auth_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('base_log', models.JSONField(default=dict, null=True, verbose_name='audit_log_base_log')),
                ('cleaned_log', models.JSONField(default=dict, verbose_name='audit_log_cleaned_log')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.device', verbose_name='audit_log_device')),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.remote', verbose_name='audit_log_remote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.user', verbose_name='audit_log_user')),
            ],
            options={
                'verbose_name': 'audit_logs',
                'verbose_name_plural': 'audit_logs',
                'db_table': 'audit_logs',
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
